buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'org.commonmark:commonmark:0.29.0'
		classpath 'org.commonmark:commonmark-ext-gfm-tables:0.29.0'
		classpath 'org.commonmark:commonmark-ext-gfm-strikethrough:0.29.0'
		classpath 'org.commonmark:commonmark-ext-gfm-alerts:0.29.0'
	}
}

plugins {
	id 'dev.architectury.loom-no-remap' version "${architectury_loom_version}" apply false
	id 'architectury-plugin' version "${architectury_plugin_version}"
	id 'com.gradleup.shadow' version "${shadow_version}" apply false
	id 'com.github.breadmoirai.github-release' version "${github_release_version}"
	id 'com.modrinth.minotaur' version "${minotaur_version}" apply false
	id 'net.darkhax.curseforgegradle' version "${curseforge_gradle_version}" apply false
}

architectury {
	minecraft = project.minecraft_version
}

allprojects {
	group = rootProject.maven_group
	version = rootProject.mod_version
}

subprojects {
	apply plugin: 'dev.architectury.loom-no-remap'
	apply plugin: 'com.gradleup.shadow'
	apply plugin: 'architectury-plugin'
	apply plugin: 'java'

	base {
		archivesName = "$rootProject.archives_name-$rootProject.minecraft_version-$project.name"
	}

	repositories{

	}

	dependencies{
		minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
	}

	java {
		withSourcesJar()

		sourceCompatibility = JavaVersion.toVersion(rootProject.mod_java)
		targetCompatibility = JavaVersion.toVersion(rootProject.mod_java)
		toolchain.languageVersion=JavaLanguageVersion.of(rootProject.mod_java as Integer)
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = rootProject.mod_java as Integer
	}

	tasks.withType(JavaExec).configureEach {
		def toolchainService = project.extensions.getByType(JavaToolchainService)
		def launcher = toolchainService.launcherFor{languageVersion = JavaLanguageVersion.of(rootProject.mod_java as Integer)}.get()

		executable = launcher.executablePath.asFile.absolutePath
	}
}

githubRelease {
	evaluationDependsOnChildren()

	token = System.getenv("GITHUB_TOKEN")
	owner = "PlagueTR"
	repo = "RetouchBrush"
	tagName = "${rootProject.mod_version}+${rootProject.minecraft_version}"
	targetCommitish = "${rootProject.branch}"
	releaseName = "Retouch Brush v${rootProject.mod_version}+${rootProject.minecraft_version}"
	body = "${rootProject.changelog}"

	def enabledPlatformsList = rootProject.enabled_platforms.split(',').collect()

	def assetsToInclude = []
	enabledPlatformsList.each { platform ->
		assetsToInclude << project(":${platform}").tasks.named("shadowJar")
	}

	releaseAssets = files(assetsToInclude)
}

tasks.register('syncReadme') {
	group "publishing"

	doLast {
		def readmeText = rootProject.file("README.md").text

		def modrinthToken = System.getenv("MODRINTH_TOKEN")
		def modrinthId = "3FhtFkZt"

		def curseForgeSession = System.getenv("CURSEFORGE_SESSION_COOKIE")
		def curseForgeAuthors = System.getenv("CURSEFORGE_AUTHORS_USER")
		def curseForgeId = "1583979"

		def client = java.net.http.HttpClient.newHttpClient()

		def modrinthPayload = [ body: readmeText.replaceAll("\r\n", "\n") ]
		def modrinthPayloadJson = groovy.json.JsonOutput.toJson(modrinthPayload)

		def modrinthURL = URI.create("https://api.modrinth.com/v2/project/${modrinthId}")

		def modrinthRequest = java.net.http.HttpRequest.newBuilder()
			.uri(modrinthURL)
			.header("Authorization", modrinthToken)
			.header("Content-Type", "application/json")
			.header("User-Agent", "Gradle")
			.method("PATCH", java.net.http.HttpRequest.BodyPublishers.ofString(modrinthPayloadJson))
			.build()

		def modrinthResponse = client.send(modrinthRequest, java.net.http.HttpResponse.BodyHandlers.ofString())

		if (modrinthResponse.statusCode() != 204) {
			throw new GradleException("Sync Readme failed for Modrinth with code ${modrinthResponse.statusCode()}: ${modrinthResponse.body()}")
		}

		def extensions = [
			org.commonmark.ext.gfm.tables.TablesExtension.create(),
			org.commonmark.ext.gfm.strikethrough.StrikethroughExtension.create(),
			org.commonmark.ext.gfm.alerts.AlertsExtension.create()
		]

		def parser = org.commonmark.parser.Parser.builder().extensions(extensions).build()
		def renderer = org.commonmark.renderer.html.HtmlRenderer.builder().extensions(extensions).build()
		def document = parser.parse(readmeText)
		def htmlDescription = renderer.render(document)

		def curseForgePayload = [
			description: htmlDescription,
			descriptionType: 1
		]
		def curseForgePayloadJson = groovy.json.JsonOutput.toJson(curseForgePayload)

		def curseForgeURL = URI.create("https://authors.curseforge.com/_api/projects/description/${curseForgeId}")

		def curseForgeRequest = java.net.http.HttpRequest.newBuilder()
			.uri(curseForgeURL)
			.header("cookie", "CobaltSession=${curseForgeSession}; AuthorsUser=${curseForgeAuthors}")
			.header("Content-Type", "application/json")
			.PUT(java.net.http.HttpRequest.BodyPublishers.ofString(curseForgePayloadJson))
			.build()

		def curseForgeResponse = client.send(curseForgeRequest, java.net.http.HttpResponse.BodyHandlers.ofString())

		if (curseForgeResponse.statusCode() != 200) {
			throw new GradleException("Sync Readme failed for CurseForge with code ${curseForgeResponse.statusCode()}: ${curseForgeResponse.body()}")
		}

	}
}