plugins {
	id 'dev.architectury.loom' version "${architectury_loom_version}" apply false
	id 'architectury-plugin' version "${architectury_plugin_version}"
	id 'com.gradleup.shadow' version "${shadow_version}" apply false
	id 'com.github.breadmoirai.github-release' version "${github_release_version}"
	id 'com.modrinth.minotaur' version "${minotaur_version}" apply false
	id 'net.darkhax.curseforgegradle' version "${curseforge_gradle_version}" apply false
}

architectury {
	minecraft = project.minecraft_version
}

allprojects {
	group = rootProject.maven_group
	version = rootProject.mod_version
}

subprojects {
	apply plugin: 'dev.architectury.loom'
	apply plugin: 'architectury-plugin'
	apply plugin: 'java'

	base {
		archivesName = "$rootProject.archives_name-$rootProject.minecraft_version-$project.name"
	}

	repositories{

	}

	dependencies{
		minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
		mappings loom.officialMojangMappings()
	}

	java {
		withSourcesJar()

		sourceCompatibility = JavaVersion.toVersion(rootProject.mod_java)
		targetCompatibility = JavaVersion.toVersion(rootProject.mod_java)
		toolchain.languageVersion=JavaLanguageVersion.of(rootProject.mod_java as Integer)
	}

	tasks.withType(JavaCompile).configureEach {
		it.options.release = rootProject.mod_java as Integer
	}

	tasks.withType(JavaExec).configureEach {
		def toolchainService = project.extensions.getByType(JavaToolchainService)
		def launcher = toolchainService.launcherFor{languageVersion = JavaLanguageVersion.of(rootProject.mod_java as Integer)}.get()

		executable = launcher.executablePath.asFile.absolutePath
	}
}

githubRelease {
	token = System.getenv("GITHUB_TOKEN")
	owner = "PlagueTR"
	repo = "RetouchBrush"
	tagName = "${rootProject.mod_version}+${rootProject.minecraft_version}"
	targetCommitish = "${rootProject.branch}"
	releaseName = "Retouch Brush v${rootProject.mod_version}+${rootProject.minecraft_version}"
	body = "${rootProject.changelog}"

	releaseAssets = files(
			project(':fabric').tasks.named('remapJar'),
			project(':forge').tasks.named('remapJar')
	)
}

tasks.register('syncReadme') {
	group "publishing"

	doLast {
		def token = System.getenv("GITHUB_TOKEN")
		def owner = "PlagueTR"
		def repo = "RetouchBrush"
		def branch = "${rootProject.branch}"

		def jsonPayload = "{\"ref\":\"${branch}\"}"

		def process = ["curl", "-s", "-X", "POST",
		               "https://github.com/${owner}/${repo}/actions/workflows/sync-readme.yml/dispatches",
		               "-H", "Authorization: Bearer ${token}",
		               "-H", "Accept: application/vnd.github+json",
		               "-H", "X-GitHub-Api-Version: 2022-11-28",
		               "-d", jsonPayload].execute()
		process.waitFor()
		if (process.exitValue() == 0) {
			println("Success")
		}
		else {
			println("Failed, Response: ${process.text}")
		}
	}
}