# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Retouch Brush
mod_description = This mod lets you cycle through paintings using the brush!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 21

maven_group = space.plague
archives_name = plaguesretouchbrush
enabled_platforms = fabric,neoforge

mod_version = 1.0.3

branch = architectury26.2
changelog = - Quilt users have to use Quilt 0.29.3-beta.1 or above since ModMenu now requires Fabric 0.17.3\n- Added swing animation when using the brush

# Minecraft properties
minecraft_version = 1.21.11

# Common
architectury_plugin_version = 3.5-SNAPSHOT
architectury_loom_version = 1.13-SNAPSHOT

shadow_version = 8.3.6
github_release_version = 2.5.2
minotaur_version = 2.+
curseforge_gradle_version = 1.3.32

common_cloth_config_version = 20.0.149

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.141.4+1.21.11

fabric_mod_menu_version = 17.0.0

# Forge
forge_version = 1.21.11-61.1.0
forge_loader_version = [61,)

# NeoForge
neoforge_version = 21.11.42
neoforge_loader_version = [1,)