# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Retouch Brush
mod_description = This mod lets you cycle through paintings using the brush!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 17

maven_group = space.plague
archives_name = plaguesretouchbrush
enabled_platforms = fabric,forge

mod_version = 1.0.2

# Minecraft properties
minecraft_version = 1.20

# Common
architectury_api_version = 9.2.14
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_version = 1.11-SNAPSHOT

shadow_version = 8.3.6

common_cloth_config_version = 11.1.136

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.83.0+1.20

fabric_mod_menu_version = 7.0.1

# Forge
forge_version = 1.20-46.0.14
forge_loader_version = [46,)

forge_better_mods_button_version = v7.0.0-1.20