# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod properties
mod_name = Plague's Retouch Brush
mod_description = This mod lets you cycle through paintings using the brush!
mod_author = Plague1337
mod_sources = https://github.com/PlagueTR/ChatTimestamps
mod_license = MIT
mod_java = 21

maven_group = space.plague
archives_name = plaguesretouchbrush
enabled_platforms = fabric,neoforge

mod_version = 1.0.2

branch = architectury26.2
changelog = - Support for Minecraft 1.21.8

# Minecraft properties
minecraft_version = 1.21.8

# Common
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_version = 1.11-SNAPSHOT

shadow_version = 8.3.6
github_release_version = 2.5.2
minotaur_version = 2.+
curseforge_gradle_version = 1.3.32

common_cloth_config_version = 19.0.147

# Fabric
fabric_loader_version = 0.17.2
fabric_api_version = 0.136.1+1.21.8

fabric_mod_menu_version = 15.0.2

# Forge
forge_version = 1.21.8-58.1.0
forge_loader_version = [58,)

# NeoForge
neoforge_version = 21.8.53
neoforge_loader_version = [1,)