plugins {
    id 'com.gradleup.shadow'
    id 'com.modrinth.minotaur'
    id 'net.darkhax.curseforgegradle'
}

loom {
    forge {
        mixinConfig "plaguesretouchbrush.mixins.json"
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven { url = "https://api.modrinth.com/maven"}
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.forge_version"

    //modImplementation "me.shedaniel:architectury-forge:$rootProject.architectury_api_version"

    modImplementation("me.shedaniel.cloth:cloth-config-forge:${rootProject.common_cloth_config_version}")

    modRuntimeOnly "maven.modrinth:better-mods-button:${rootProject.forge_better_mods_button_version}-Forge"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'transformProductionForge')
}

processResources {
    inputs.property 'forge_loader_version', rootProject.forge_loader_version
    inputs.property 'mod_license', rootProject.mod_license
    inputs.property 'mod_version', rootProject.mod_version
    inputs.property 'mod_name', rootProject.mod_name
    inputs.property 'mod_author', rootProject.mod_author
    inputs.property 'mod_desc', rootProject.mod_description
    inputs.property 'minecraft_version', rootProject.minecraft_version

    filesMatching('META-INF/mods.toml') {
        expand([
            'forge_loader_version': inputs.properties.forge_loader_version,
            'mod_license': inputs.properties.mod_license,
            'mod_version': inputs.properties.mod_version,
            'mod_name': inputs.properties.mod_name,
            'mod_author': inputs.properties.mod_author,
            'mod_desc': inputs.properties.mod_desc,
            'minecraft_version': inputs.properties.minecraft_version,
        ])
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "retouch-brush"
    versionNumber = "${rootProject.mod_version}+${rootProject.minecraft_version}-Forge"
    uploadFile = remapJar
    gameVersions = ["${rootProject.minecraft_version}"]
    loaders = ["forge"]
    dependencies {
        optional.project("cloth-config")
    }
    changelog = "${rootProject.changelog}"
}

tasks.named('modrinthSyncBody') {
    group = null
}

tasks.register('curseforge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    group "publishing"

    apiToken = System.getenv("CURSEFORGE_TOKEN")

    def mainFile = upload(1583979, remapJar)
    mainFile.displayName = "${rootProject.mod_version}+${rootProject.minecraft_version}-Forge"
    mainFile.changelog = "${rootProject.changelog}"
    mainFile.changelogType = "markdown"
    mainFile.releaseType = net.darkhax.curseforgegradle.Constants.RELEASE_TYPE_RELEASE
    mainFile.addGameVersion("${rootProject.minecraft_version}")
    mainFile.addModLoader("Forge")

    mainFile.addOptional("cloth-config")
}