modLoader = "javafml"
loaderVersion = "${neoforge_loader_version}"
license = "${mod_license}"

[[mods]]
modId = "plaguesretouchbrush"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_desc}
'''
logoFile = "icon.png"

[[dependencies.plaguesretouchbrush]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.plaguesretouchbrush]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "plaguesretouchbrush.mixins.json"
